import 'package:hive/hive.dart';
import '../models/product.dart';
import '../models/customer.dart';
import '../models/payment.dart';
import '../models/credit_plan.dart';
import '../models/transaction.dart';
import '../models/store_profile.dart';

/// Register all Hive type adapters
/// Must be called before opening any Hive boxes
void registerHiveAdapters() {
  // Register model adapters (generated by hive_generator)
  Hive.registerAdapter(ProductAdapter());
  Hive.registerAdapter(CustomerAdapter());
  Hive.registerAdapter(PaymentMethodAdapter());
  Hive.registerAdapter(PaymentAdapter());
  Hive.registerAdapter(CreditPlanAdapter());
  Hive.registerAdapter(TransactionItemAdapter());
  Hive.registerAdapter(TransactionAdapter());
  Hive.registerAdapter(StoreProfileAdapter());
}
